#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $LYNX_REPO == "LYNXBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RFQU0tTFlOWC1PUC9MWU5YLVVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $LYNX_REPO == "LYNXBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RFQU0tTFlOWC1PUC9MWU5YLVVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $LYNX_REPO =~ $regex ]]
    then
        if [[ $LYNX_REPO_BRANCH ]]
        then
            echo "${LYNX_REPO}/archive/${LYNX_REPO_BRANCH}.zip"
        else
            echo "${LYNX_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RFQU0tTFlOWC1PUC9MWU5YLVVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="lynxbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    MAFIAPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $MAFIAPATH
    echo "    Starting LynxBot    "
    echo "
                          
██╗░░░░░██╗░░░██╗███╗░░██╗██╗░░██╗
██║░░░░░╚██╗░██╔╝████╗░██║╚██╗██╔╝
██║░░░░░░╚████╔╝░██╔██╗██║░╚███╔╝░
██║░░░░░░░╚██╔╝░░██║╚████║░██╔██╗░
███████╗░░░██║░░░██║░╚███║██╔╝╚██╗
╚══════╝░░░╚═╝░░░╚═╝░░╚══╝╚═╝░░╚═╝
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
